import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn, Index } from 'typeorm';
import { User } from './user.entity';
import { Organization } from './organization.entity';

export enum AuditLogStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum AuditAction {
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_LOGOUT_ALL = 'AUTH_LOGOUT_ALL',
  AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_PASSWORD_RESET_REQUEST = 'AUTH_PASSWORD_RESET_REQUEST',
  AUTH_PASSWORD_RESET_VERIFY = 'AUTH_PASSWORD_RESET_VERIFY',
  AUTH_PASSWORD_RESET_COMPLETE = 'AUTH_PASSWORD_RESET_COMPLETE',
  AUTH_ACCOUNT_INVITE_CREATED = 'AUTH_ACCOUNT_INVITE_CREATED',
  AUTH_ACCOUNT_INVITE_SENT = 'AUTH_ACCOUNT_INVITE_SENT',
  AUTH_ACCOUNT_INVITE_USED = 'AUTH_ACCOUNT_INVITE_USED',
  AUTH_ACCOUNT_INVITE_EXPIRED = 'AUTH_ACCOUNT_INVITE_EXPIRED',
  AUTH_ACCOUNT_ACTIVATED = 'AUTH_ACCOUNT_ACTIVATED',
  AUTH_ACCOUNT_DEACTIVATED = 'AUTH_ACCOUNT_DEACTIVATED',

  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_STATUS_UPDATED = 'USER_STATUS_UPDATED',
  USER_ROLE_UPDATED = 'USER_ROLE_UPDATED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_PHONE_UPDATED = 'USER_PHONE_UPDATED',
  USER_EMAIL_UPDATED = 'USER_EMAIL_UPDATED',
  USER_AVATAR_UPDATED = 'USER_AVATAR_UPDATED',
  USER_LOGIN_DISABLED = 'USER_LOGIN_DISABLED',
  USER_LOGIN_ENABLED = 'USER_LOGIN_ENABLED',

  ORG_CREATED = 'ORG_CREATED',
  ORG_UPDATED = 'ORG_UPDATED',
  ORG_DELETED = 'ORG_DELETED',
  ORG_STATUS_UPDATED = 'ORG_STATUS_UPDATED',
  ORG_PARENT_CHANGED = 'ORG_PARENT_CHANGED',
  ORG_TYPE_CHANGED = 'ORG_TYPE_CHANGED',

  ORG_MEMBER_ADDED = 'ORG_MEMBER_ADDED',
  ORG_MEMBER_UPDATED = 'ORG_MEMBER_UPDATED',
  ORG_MEMBER_REMOVED = 'ORG_MEMBER_REMOVED',
  ORG_MEMBER_ROLE_CHANGED = 'ORG_MEMBER_ROLE_CHANGED',
  ORG_MEMBER_STATUS_CHANGED = 'ORG_MEMBER_STATUS_CHANGED',

  DEVICE_CREATED = 'DEVICE_CREATED',
  DEVICE_UPDATED = 'DEVICE_UPDATED',
  DEVICE_DELETED = 'DEVICE_DELETED',
  DEVICE_STATUS_UPDATED = 'DEVICE_STATUS_UPDATED',
  DEVICE_ASSIGNED = 'DEVICE_ASSIGNED',
  DEVICE_UNASSIGNED = 'DEVICE_UNASSIGNED',
  DEVICE_PROVISIONED = 'DEVICE_PROVISIONED',
  DEVICE_UNPROVISIONED = 'DEVICE_UNPROVISIONED',
  DEVICE_TRANSFERRED = 'DEVICE_TRANSFERRED',

  DEVICE_REQUEST_CREATED = 'DEVICE_REQUEST_CREATED',
  DEVICE_REQUEST_UPDATED = 'DEVICE_REQUEST_UPDATED',
  DEVICE_REQUEST_APPROVED = 'DEVICE_REQUEST_APPROVED',
  DEVICE_REQUEST_REJECTED = 'DEVICE_REQUEST_REJECTED',
  DEVICE_REQUEST_CANCELLED = 'DEVICE_REQUEST_CANCELLED',
  DEVICE_REQUEST_DELETED = 'DEVICE_REQUEST_DELETED',

  ADDRESS_CREATED = 'ADDRESS_CREATED',
  ADDRESS_UPDATED = 'ADDRESS_UPDATED',
  ADDRESS_DELETED = 'ADDRESS_DELETED',
  LOCATION_CREATED = 'LOCATION_CREATED',
  LOCATION_UPDATED = 'LOCATION_UPDATED',
  LOCATION_DELETED = 'LOCATION_DELETED',

  TELEMETRY_INGEST_SUCCESS = 'TELEMETRY_INGEST_SUCCESS',
  TELEMETRY_INGEST_FAILED = 'TELEMETRY_INGEST_FAILED',
  TELEMETRY_EXPORT = 'TELEMETRY_EXPORT',
  TELEMETRY_DELETED = 'TELEMETRY_DELETED',

  COST_CREATED = 'COST_CREATED',
  COST_UPDATED = 'COST_UPDATED',
  COST_DELETED = 'COST_DELETED',
  COST_HISTORY_CREATED = 'COST_HISTORY_CREATED',
  COST_HISTORY_UPDATED = 'COST_HISTORY_UPDATED',
  COST_HISTORY_DELETED = 'COST_HISTORY_DELETED',

  CONTENT_CREATED = 'CONTENT_CREATED',
  CONTENT_UPDATED = 'CONTENT_UPDATED',
  CONTENT_DELETED = 'CONTENT_DELETED',
  CONTENT_PUBLISHED = 'CONTENT_PUBLISHED',
  CONTENT_UNPUBLISHED = 'CONTENT_UNPUBLISHED',

  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
  FILE_REPLACED = 'FILE_REPLACED',

  REPORT_GENERATED = 'REPORT_GENERATED',
  REPORT_EXPORTED = 'REPORT_EXPORTED',
  REPORT_DELETED = 'REPORT_DELETED',

  SYSTEM_CONFIG_UPDATED = 'SYSTEM_CONFIG_UPDATED',
  SYSTEM_MAINTENANCE_MODE_ON = 'SYSTEM_MAINTENANCE_MODE_ON',
  SYSTEM_MAINTENANCE_MODE_OFF = 'SYSTEM_MAINTENANCE_MODE_OFF',
  DATA_BACKUP_CREATED = 'DATA_BACKUP_CREATED',
  DATA_RESTORE_EXECUTED = 'DATA_RESTORE_EXECUTED',
  DATA_MIGRATION_RUN = 'DATA_MIGRATION_RUN',
}

export enum AuditTargetType {
  USER = 'USER',
  ORGANIZATION = 'ORGANIZATION',
  ORGANIZATION_MEMBER = 'ORGANIZATION_MEMBER',
  DEVICE = 'DEVICE',
  DEVICE_REQUEST = 'DEVICE_REQUEST',
  LOCATION = 'LOCATION',
  ADDRESS = 'ADDRESS',
  TELEMETRY_READING = 'TELEMETRY_READING',
  COST = 'COST',
  COST_HISTORY = 'COST_HISTORY',
  CONTENT = 'CONTENT',
  REFRESH_SESSION = 'REFRESH_SESSION',
  RESET_OTP = 'RESET_OTP',
  ACCOUNT_INVITE = 'ACCOUNT_INVITE',
  AUDIT_LOG = 'AUDIT_LOG',
  SYSTEM_CONFIG = 'SYSTEM_CONFIG',
  FILE_UPLOAD = 'FILE_UPLOAD',
  REPORT = 'REPORT',
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
}

@Entity('audit_logs')
export class AuditLog {
  @PrimaryGeneratedColumn('uuid', { name: 'audit_id' })
  auditId!: string;

  @Column({ name: 'actor_user_id', type: 'uuid' })
  actorUserId!: string;

  @Column({ name: 'actor_org_id', type: 'uuid', nullable: true })
  actorOrgId?: string | null;

  @Column({ name: 'action', type: 'enum', enum: AuditAction })
  action!: AuditAction;

  @Column({ name: 'target_type', type: 'enum', enum: AuditTargetType })
  targetType!: AuditTargetType;

  @Column({ name: 'target_id', type: 'uuid', nullable: true })
  targetId?: string | null;

  @Column({ name: 'status', type: 'enum', enum: AuditLogStatus })
  status!: AuditLogStatus;

  @Column({ name: 'ip', type: 'varchar', nullable: true })
  ip?: string | null;

  @Column({ name: 'user_agent', type: 'varchar', nullable: true })
  userAgent?: string | null;

  @Column({ name: 'metadata', type: 'jsonb', nullable: true })
  metadata?: Record<string, any> | null;

  @Index()
  @Column({ name: 'created_at', type: 'timestamptz', default: () => 'CURRENT_TIMESTAMP' })
  createdAt!: Date;

  @ManyToOne(() => User, (u) => u.auditLogs, { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'actor_user_id', referencedColumnName: 'userId' })
  actorUser!: User;

  @ManyToOne(() => Organization, (o) => o.auditLogs, { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'actor_org_id', referencedColumnName: 'orgId' })
  actorOrg?: Organization | null;
}
